name: Continuous Integration Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name:
      run: nuget sources add -name GitHub -source https://nuget.pkg.github.com/DKE-Data/index.json -username saschadoemer -password ${{ GITHUB_TOKEN }}

    - name: Build with dotnet
      run: dotnet build --configuration Release
